SET NAMES utf8mb4;

INSERT INTO `question` (`id`, `name`, `question_text`, `weight`, `description`, `question_order`) VALUES
(1,	'Author is the same',	'Is the code authored by the same person?',	0.5,	'',	1),
(2,	'3rd party',	'Does it integrate with third-party software?',	0.3,	'',	2),
(3,	'login system',	'Does the it require a login system?',	0.2,	'',	3),
(4,	'Email templating',	'Will it require email templating?',	0.2,	'',	4),
(5,	'Custom Design Level',	'What is the graphic design effort level (0-10)?',	0.6,	'',	5),
(6,	'Number of pages',	'How many different screens?',	0.7,	'Different screens include pop-ups and data regenerated  in the same screen.',	6),
(7,	'Code base age',	'How old is the code base (in months)?',	0.7,	'The number of months a code base has since start.',	7),
(8,	'General complexity',	'How complex would you rate this code (0-10)?',	0.8,	'',	8),
(9,	'2fa',	'Two Factor Authentication required?',	0.5,	'',	9),
(10,	'Security level',	'What would the security level be?',	0.4,	'',	10),
(11,	'eCommerce',	'Is this for or a complete eCommerce piece of software?',	0.7,	'',	11),
(12,	'Video',	'Will it include video?',	0.2,	'',	12),
(13,	'CMS',	'Is this a part or the start of a CMS?',	0.6,	NULL,	100),
(14,	'Backend Admin',	'Will it require backend administration?',	0.7,	NULL,	120),
(15,	'Statistics',	'Will it require statistical analysis or a dashboard of the sorts?',	0.2,	NULL,	150),
(16,	'Google Analytics',	'Will it require google analytics',	0.1,	NULL,	200),
(17,	'Custom Analytics',	'Will it require custom analytics (yes/no)',	0.6,	NULL,	210),
(18,	'Data Migration',	'Will it require data migration of sorts?',	0.5,	NULL,	220),
(19,	'Existing database',	'Does it make use of an existing database?',	0.8,	NULL,	240),
(20,	'Server control',	'Do we have control over all environment servers?',	0.9,	NULL,	300),
(21,	'User management',	'Does it require user management?',	0.6,	NULL,	310),
(22,	'Notifications',	'Will it require a notification system?',	0.3,	NULL,	330),
(23,	'User walls',	'Will it make use of a user forum \"wall\"?',	0.5,	NULL,	350),
(24,	'Time constraints?',	'Are there hard time constraints?',	0.8,	NULL,	400),
(25,	'Number of developers',	'How many developers will be working on this?',	0.5,	NULL,	450),
(26,	'Domain familiarity',	'Does the team or developer have familiarity with the business domain?',	0.6,	NULL,	500);
