version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - /var/application/estimator2018:/var/application/estimator2018